FROM python_sandbox_vanilla:latest

COPY requirements_jupyter.txt ./requirements.txt

RUN --mount=type=cache,target=/root/.cache/pip \
    pip install --no-cache-dir -r requirements.txt

RUN echo "echo jupyter notebook --allow-root --ip=0.0.0.0" >> ~/.bashrc